export const navigationItems = [
  { href: '/', label: 'Dashboard' },
  { href: '/recent-updates', label: 'Recent Updates' },
  { href: '/skill-coach', label: 'Skill Coach' },
  { href: '/focus', label: 'Focus' },
  { href: '/scheduler', label: 'PD Scheduler' },
  { href: '/modules', label: 'Modules' },
  { href: '/certifications/aplus-core-2', label: 'A+ Core 2' },
  { href: '/practice-exam', label: 'Practice Exam' },
  { href: '/scenarios', label: 'Scenario Lab' },
  { href: '/simulations/network', label: 'Network Map' },
  { href: '/simulations/classroom-desk', label: 'Classroom Desk' },
  { href: '/simulations/roleplay', label: 'Roleplay Bot' },
  { href: '/peer-review', label: 'Peer Review' },
  { href: '/voice-to-ticket', label: 'Voice-to-Ticket' },
  { href: '/hardware', label: 'Hardware' },
  { href: '/cheat-sheets', label: 'Cheat Sheets' },
  { href: '/ticket-data-import', label: 'Ticket Data' },
  { href: '/search', label: 'Search' },
  { href: '/feedback-log', label: 'Feedback Log' },
  { href: '/due-today', label: 'Due Today' },
  { href: '/usage-insights', label: 'Usage Insights' },
  { href: '/strict-quiz', label: 'Strict Quiz' },
  { href: '/pd-log', label: 'PD Log' },
  { href: '/certificates', label: 'Certificates' },
  { href: '/academic-pd', label: 'Academic PD' },
  { href: '/evidence-pack', label: 'Evidence Pack' },
  { href: '/knowledge-base-lab', label: 'KB Lab' },
  { href: '/kb-sync', label: 'KB Sync' },
  { href: '/error-log', label: 'Error Log' },
  { href: '/readiness', label: 'Readiness' },
  { href: '/supervisor', label: 'Supervisor' },
  { href: '/mobile-qa', label: 'Mobile QA' },
  { href: '/trainer-guide', label: 'Trainer Guide' },
  { href: '/admin', label: 'Admin Hub' },
  { href: '/sync', label: 'Sync' },
  { href: '/settings', label: 'Settings' }
];
